# Generated by Django 4.1.2 on 2022-10-05 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BookApp', '0003_review'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name_plural': 'reviews'},
        ),
    ]
