# Generated by Django 4.1.2 on 2022-10-05 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BookApp', '0004_alter_review_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={},
        ),
    ]
